### ISSUE TITLE
使用Curl上传文件之后 返回Internal Server Error 

### ISSUE THREAD

**Issue by pysio2007** [GlobeMC/pastemc#1]
# 遇到的的问题
使用Curl上传文件之后 返回Internal Server Error 但是S3存储上已有文件 fetch查询到 
使用的指令: `curl -X POST   -F "file=@./test.txt"   -F "format_type=txt"   http://38.46.30.41:8000/upload`
查询的URL [http://38.46.**.**:8000/fetch/01HS1G8KM0CER6QD072TW2TXRX](http://38.46.**.**:8000/fetch/01HS1G8KM0CER6QD072TW2TXRX)
## 报错
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/pastemc/pastemc/modules/upload.py", line 55, in upload_file
    FileObjectResponse.public(file_id=file_id).model_dump(),
  File "/root/pastemc/pastemc/models/common.py", line 52, in public
    last_modified=ULID.from_str(file_id).datetime.astimezone(),
  File "/usr/local/lib/python3.10/dist-packages/ulid/__init__.py", line 41, in wrapped
    raise ValueError(message)
ValueError: Value has to be of type str
```

**Comment by SerinaNya** [comment]
已在 https://github.com/GlobeMC/pastemc/commit/048a03bbd6aa2abf075b6d273f692fc3300f9708 中修复
